# Generated by Django 4.2 on 2024-11-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeValue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('TypeValueName', models.CharField(max_length=50)),
                ('TypeValueKind', models.CharField(max_length=10)),
                ('ValCode', models.CharField(max_length=3)),
                ('IsActive', models.SmallIntegerField()),
            ],
            options={
                'db_table': '"public"."TypeValue"',
            },
        ),
        migrations.AddConstraint(
            model_name='typevalue',
            constraint=models.CheckConstraint(check=models.Q(('IsActive__in', [0, 1])), name='is_active_check'),
        ),
    ]
